# Generated by Django 2.2 on 2020-05-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20200501_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='token',
            field=models.CharField(default='5s5', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='publish'),
        ),
    ]
