# Generated by Django 2.2 on 2020-05-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
