# Generated by Django 2.2 on 2020-05-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_auto_20200502_1542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
