# Generated by Django 2.2 on 2020-06-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0015_auto_20200605_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=250),
        ),
    ]
